version: '3.1'

services:

  web:
    build: .
    ports:
      - "3294:80"
    depends_on:
      - db

  db:
    image: mysql:5.6.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
